# docker-compose.prod.yml
version: "3.8"

services:
  web:
    build: .
    image: coldmail-prod:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=0
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - GS_BUCKET_NAME=${GS_BUCKET_NAME}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - gcp_creds:/secrets/gcp-credentials
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  gcp_creds:
