# Generated by Django 5.2.3 on 2025-06-20 19:16

import django.db.models.deletion
import django_nanoid.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiMail",
            fields=[
                (
                    "id",
                    django_nanoid.models.NANOIDField(
                        alphabetically=None,
                        prefix=None,
                        primary_key=True,
                        secure_generated=True,
                        serialize=False,
                        size=None,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeData",
            fields=[
                (
                    "id",
                    django_nanoid.models.NANOIDField(
                        alphabetically=None,
                        prefix=None,
                        primary_key=True,
                        secure_generated=True,
                        serialize=False,
                        size=None,
                        unique=True,
                    ),
                ),
                ("target_company", models.CharField(max_length=255)),
                ("target_role", models.CharField(max_length=255)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("Formal", "Formal"),
                            ("Casual", "Casual"),
                            ("Persuasive", "Persuasive"),
                            ("Concise", "Concise"),
                            ("Enthusiastic", "Enthusiastic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resume_files/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gemini_mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="api.geminimail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
