# Generated by Django 5.2.3 on 2025-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedata",
            name="resume_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumedata",
            name="resume_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
